### ISSUE TITLE
template v2.2.0 does not have a package available for your current platform, darwin_arm64

### ISSUE THREAD

**Issue by jkolyer** [hashicorp/learn-terraform-provisioning#18]
This tutorial uses the deprecated `template_file` and does not work on Mac M1s.

https://discuss.hashicorp.com/t/template-v2-2-0-does-not-have-a-package-available-mac-m1/35099

https://github.com/hashicorp/terraform-provider-template/issues/85

**Comment by alanszlosek** [comment]
This should now be fixed by PR #20 . Thanks for reporting!
