### ISSUE TITLE
Provision Infrastructure with Cloud-Init: "ssh: Could not resolve hostname..."

### ISSUE THREAD

**Issue by ybod** [hashicorp/learn-terraform-provisioning#9]
Every time I try to execute command from `Provision Infrastructure with Cloud-Init: Verify your instance` part of the guide https://learn.hashicorp.com/tutorials/terraform/cloud-init#verify-your-instance
```
ssh terraform@$(echo "aws_instance.web.public_ip" | terraform console) -i ../tf-cloud-init
```

I get an SSH error in response:
```
ssh: Could not resolve hostname "X.XXX.XX.XX": nodename nor servname provided, or not known
```

probably`echo "aws_instance.web.public_ip" | terraform console` returns carriage return symbol that breaks the scrip? 
The only way for me to get this command working is to use following script isntead:

```
ssh terraform@$(terraform output -raw public_ip) -i ../tf-cloud-init
```

**Comment by tr0njavolta** [comment]
Thanks @ybod updated!
